apiVersion: project.openshift.io/v1
kind: Project
metadata:
  name: gitea
---
apiVersion: pfe.rhpds.com/v1
kind: Gitea
metadata:
  name: gitea-workshop
  namespace: gitea
spec:
  giteaSsl: true
  giteaAdminUser: admin
  giteaAdminPassword: openshift
  giteaAdminEmail: admin@workshop.com
  giteaCreateUsers: true
  giteaGenerateUserFormat: "student%d"
  giteaUserNumber: 3
  giteaUserPassword: openshift
